#OGFmakefile for src subdir

OGFSources =	commandArgs.cpp				\
				textUtils.cpp				\
				OGFEvetns.cpp				\
				gameLoop.cpp				\
				math.cpp					\
				OSFile.cpp					\
				prefs.cpp					\
				OGFTimer.cpp				\
				parser.cpp					\
				utils.cpp					

OGFSources_extended =	3dUtils.cpp					\
						animMesh.cpp				\
						input.cpp					\
						clouds.cpp					\
						displayListManager.cpp		\
						drawlist.cpp				\
						fileLoaders.cpp				\
						fontManager.cpp				\
						3dView.cpp					\
						input.cpp					\
						panelManager.cpp			\
						skybox.cpp					\
						soundmanager.cpp			\
						textureManager.cpp			\
						viewCull.cpp 